# ~/.config/starship.toml
format = """[$username$directory$rust$elixir$nodejs$python$haskell$package$git_branch$git_status$character](bold green)"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false


[character] # The name of the module we are configuring is "character"
success_symbol = "[位](bold green)" # The "success_symbol" segment is being set to "位" with the color "bold green"
error_symbol = "[位](bold red)" # The "error_symbol" segment is being set to "位" with the color "bold green"

